name: 'lego_analytics_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  lego_analytics_dbt_project:  # This must match the `name` field above
    lego_analytics:
      # I’m intentionally not specifying a schema here because I set the schema in dbt Cloud environment instead
      # This prevents double-prefixing like lego_selfserve_lego_selfserve
      +materialized: table  # (optional) all models as tables
