name: 'lego_analytics_dbt_project'
version: '1.0.0'
config-version: 2
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  lego_analytics_dbt_project:
    +database: lego_analytics     # UC catalog
    +schema: lego_selfserve       # Desired schema (will duplicate unless we override macro)
    +materialized: table
    lego_analytics: {}
    lego_source: {}
